// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDVqCszF0d4REgRU3FKVWGBz7SIoACeY',
    appId: '1:840217179788:web:adbfecb1ca3c6f4863eda9',
    messagingSenderId: '840217179788',
    projectId: 'tugas-apk',
    authDomain: 'tugas-apk.firebaseapp.com',
    storageBucket: 'tugas-apk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBQkcNtpmALOt42W5i01tYJTHWcoAs1o',
    appId: '1:840217179788:android:2288ec346cb58d0963eda9',
    messagingSenderId: '840217179788',
    projectId: 'tugas-apk',
    storageBucket: 'tugas-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaItcNKFXW3FGzRJYcxxK2yFZvA85SIN0',
    appId: '1:840217179788:ios:7c2392560ce9254563eda9',
    messagingSenderId: '840217179788',
    projectId: 'tugas-apk',
    storageBucket: 'tugas-apk.firebasestorage.app',
    iosBundleId: 'com.example.intip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaItcNKFXW3FGzRJYcxxK2yFZvA85SIN0',
    appId: '1:840217179788:ios:7c2392560ce9254563eda9',
    messagingSenderId: '840217179788',
    projectId: 'tugas-apk',
    storageBucket: 'tugas-apk.firebasestorage.app',
    iosBundleId: 'com.example.intip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIDVqCszF0d4REgRU3FKVWGBz7SIoACeY',
    appId: '1:840217179788:web:02db3405455e2a4d63eda9',
    messagingSenderId: '840217179788',
    projectId: 'tugas-apk',
    authDomain: 'tugas-apk.firebaseapp.com',
    storageBucket: 'tugas-apk.firebasestorage.app',
  );
}
